name: in_app_review
publish_to: none
description: Flutter plugin for showing the In-App Review/System Rating pop up on Android, iOS and MacOS. It makes it easy for users to rate your app.
version: 2.0.12

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  
  in_app_review_platform_interface: 2.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.5.0
  plugin_platform_interface: 2.1.8

dependency_overrides: 
  in_app_review_platform_interface:
    git:
      url: https://github.com/AndreLuizNogueira/in_app_review.git
      path: in_app_review_platform_interface


flutter:
  plugin:
    platforms:
      android:
        package: dev.britannio.in_app_review
        pluginClass: InAppReviewPlugin
      ios:
        pluginClass: InAppReviewPlugin
      macos:
        pluginClass: InAppReviewPlugin
    
screenshots:
  - description: A screenshot of the iOS rating pop-up.
    path: screenshots/ios.png