name: in_app_review_platform_interface
publish_to: none
description: A common platform interface for the in_app_review plugin.
version: 2.0.6

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: 6.3.2
  plugin_platform_interface: 2.1.8
  platform: 3.1.6

  
dev_dependencies:
  flutter_test:
    sdk: flutter
    